baseURL: https://nehadagade.netlify.app/
languageCode: en-us
title: Neha
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get to know me!
    
    subtitle: |-
      I'm currently pursuing my Masters in Analytics and Management at London Business School.
     
     #   A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
     #   AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, I'm Neha!
  blog: 
  contact:
    address:
      - city: London, W1H 1FF
        country: United Kingdom
        street: 32 York Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ndagade.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7831501499
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Neha Dagade
    enable: yes
    quicklinks:
      #- alt: HTML5 UP
      #  text: 'Design: '
      #  url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/sai.nehadagade
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/_.neha19._/
      - icon: fa-github
        label: GitHub
        url: https://github.com/nehadagade
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/neha-dagade/
  image: ''
  name: Neha Dagade
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
      #  url: blogs/ipsum
      #- name: Elements
      #  url: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: Neha's Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: About me.jpg
        subtitle: Who am I?
        title: About Me
        url: blogs/aboutme
      - image: My CV.jpg
        subtitle: Learn more about more career profile and aspirations
        title: My CV
        url: blogs/NehaDagade_CV.html
      - image: high school health.jpeg
        #subtitle: Lorem Etiam Nullam
        title: Youth Risk Behavior Surveillance
        url: blogs/youth
      - image: climate change.jpeg
        #subtitle: Nisl Sed Aliquam
        title: Climate change and temperature anomalies
        url: blogs/climate
      - image: sanfran.jpeg
        #subtitle: Ipsum Dolor Sit Amet
        title: Rents in San Francisco
        url: blogs/rent
      - image: retail sales.jpeg
        #subtitle: Feugiat Amet Tempus
        title: Analysis of weekly sales of Retailer
        url: blogs/retailer
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Curious, passionate and determined. A stickler for perfection and professionalism who thrives on challenge. Born in India and raised in Malaysia. Econs and Stats undergrad, presently a LBS MAM'23 student keen on exploring opportunities in finance, tech and insurance.
      \r\nPassionate about analytics and problem solving.  \r\n    Food, fashion and travel lover. Looking to meet new people, collaborate, inspire, explore and make lifelong connections."
    title: A quick Intro 
    url: blogs
